# Generated by Django 6.0.4 on 2026-06-07 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, verbose_name='Biografia')),
                ('campus', models.CharField(blank=True, max_length=100, verbose_name='Campus')),
                ('matricula', models.CharField(blank=True, max_length=14, verbose_name='Matrícula')),
                ('tipo_vinculo', models.CharField(blank=True, max_length=50, verbose_name='Tipo de Vínculo')),
                ('foto_url', models.URLField(blank=True, verbose_name='Foto')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
